# Generated by Django 3.2.5 on 2022-06-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvmaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='columns',
        ),
    ]
