# Generated by Django 3.2.5 on 2022-06-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmaker', '0003_schema_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('integer', 'Integer'), ('fullname', 'Full Name'), ('address', 'Address'), ('email', 'Email'), ('phone', 'Phone Number')], max_length=50),
        ),
    ]
