# Generated by Django 3.2.5 on 2022-06-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmaker', '0005_auto_20220615_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='columns',
            field=models.ManyToManyField(to='csvmaker.Column'),
        ),
    ]
