# Generated by Django 3.2.12 on 2022-06-18 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvmaker', '0010_dataset_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='author',
        ),
    ]
